/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilFeedCard {
        /**
          * @default 1
         */
        "postId": number;
    }
}
declare global {
    interface HTMLStencilFeedCardElement extends Components.StencilFeedCard, HTMLStencilElement {
    }
    var HTMLStencilFeedCardElement: {
        prototype: HTMLStencilFeedCardElement;
        new (): HTMLStencilFeedCardElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-feed-card": HTMLStencilFeedCardElement;
    }
}
declare namespace LocalJSX {
    interface StencilFeedCard {
        /**
          * @default 1
         */
        "postId"?: number;
    }

    interface StencilFeedCardAttributes {
        "postId": number;
    }

    interface IntrinsicElements {
        "stencil-feed-card": Omit<StencilFeedCard, keyof StencilFeedCardAttributes> & { [K in keyof StencilFeedCard & keyof StencilFeedCardAttributes]?: StencilFeedCard[K] } & { [K in keyof StencilFeedCard & keyof StencilFeedCardAttributes as `attr:${K}`]?: StencilFeedCardAttributes[K] } & { [K in keyof StencilFeedCard & keyof StencilFeedCardAttributes as `prop:${K}`]?: StencilFeedCard[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-feed-card": LocalJSX.IntrinsicElements["stencil-feed-card"] & JSXBase.HTMLAttributes<HTMLStencilFeedCardElement>;
        }
    }
}
